### ISSUE TITLE
卯師傅沒有正常觸發。

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#14]
在此回和內，吃了甜甜釀花雞後卯師傅沒有正常觸發，骰子數量沒變，也沒有成功索引一張食物，支援區也顯示未觸發。

![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/f5687f7b-02f0-4a86-81cd-36cddd96e5d9)

![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/afc337a9-0202-4b5a-9ce3-794d34fe089a)

並且在後續嘗試吃下烤蘑菇披薩進行後續測試時，產生了錯誤。
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/6e4b45ae-556c-4678-9b5c-8d3eb0051f02)

2024-07-04 16:03:07.506 | INFO     | genius_invocation.game.game:step:298 - in main game
Traceback (most recent call last):
  File "C:\Users\jeffr\OneDrive\桌面\學業\研究所\Genius-Invokation-main\Genius-Invokation-main\genius_invocation\main.py", line 248, in <module>
    game.step(action)
  File "c:\users\jeffr\onedrive\桌面\學業\研究所\genius-invokation-main\genius-invokation-main\genius_invocation\game\game.py", line 317, in step
    game_for_plan.resolve_action(action)
  File "c:\users\jeffr\onedrive\桌面\學業\研究所\genius-invokation-main\genius-invokation-main\genius_invocation\game\game.py", line 170, in resolve_action
    active_player.play_card(self)
  File "c:\users\jeffr\onedrive\桌面\學業\研究所\genius-invokation-main\genius-invokation-main\genius_invocation\game\player.py", line 228, in play_card
    card.on_played(game)
  File "c:\users\jeffr\onedrive\桌面\學業\研究所\genius-invokation-main\genius-invokation-main\genius_invocation\card\action\event\foods\Mushroom_Pizza.py", line 44, in on_played
    super().on_played(game)
  File "c:\users\jeffr\onedrive\桌面\學業\研究所\genius-invokation-main\genius-invokation-main\genius_invocation\card\action\event\base.py", line 24, in on_played
    if self.food_entity != None:
       ^^^^^^^^^^^^^^^^
AttributeError: 'Mushroom_Pizza' object has no attribute 'food_entity'

**Comment by WentDong** [comment]
Fixed!
